# Demonstration of Ngram Method

In [1]:
# Small Example

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame({'text':['people watch campus','campus watch campus','people write comment','campus write comment'],'output':[1,1,0,0]})

In [4]:
df

text  output
0   people watch campus       1
1   campus watch campus       1
2  people write comment       0
3  campus write comment       0

In [5]:
# Bigram
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

bow = cv.fit_transform(df['text']).toarray()

# Vocabulary
print(cv.vocabulary_)

# print(bow[0].toarray())
print(bow[0])

{'people watch': 2, 'watch campus': 4, 'campus watch': 0, 'people write': 3, 'write comment': 5, 'campus write': 1}
[0 0 1 0 1 0]


In [6]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(1,2)) 

bow = cv.fit_transform(df['text']).toarray()

# Vocabulary
print(cv.vocabulary_)

# print(bow[0].toarray())
print(bow[0])

{'people': 4, 'watch': 7, 'campus': 0, 'people watch': 5, 'watch campus': 8, 'campus watch': 1, 'write': 9, 'comment': 3, 'people write': 6, 'write comment': 10, 'campus write': 2}
[1 0 0 0 1 1 0 1 1 0 0]


In [7]:
# Trigram
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(3,3))

bow = cv.fit_transform(df['text']).toarray()

# Vocabulary
print(cv.vocabulary_)

# print(bow[0].toarray())
print(bow[0])

{'people watch campus': 2, 'campus watch campus': 0, 'people write comment': 3, 'campus write comment': 1}
[0 0 1 0]


In [8]:
# Quadgram
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(4,4))

bow = cv.fit_transform(df['text']).toarray()

# Vocabulary
print(cv.vocabulary_)

# print(bow[0].toarray())
print(bow[0])

ValueError: empty vocabulary; perhaps the documents only contain stop words

In [9]:
# 
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(1,3))

bow = cv.fit_transform(df['text']).toarray()

# Vocabulary
print(cv.vocabulary_)

# print(bow[0].toarray())
print(bow[0])

{'people': 6, 'watch': 11, 'campus': 0, 'people watch': 7, 'watch campus': 12, 'people watch campus': 8, 'campus watch': 1, 'campus watch campus': 2, 'write': 13, 'comment': 5, 'people write': 9, 'write comment': 14, 'people write comment': 10, 'campus write': 3, 'campus write comment': 4}
[1 0 0 0 0 0 1 1 1 0 0 1 1 0 0]
